remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - index.md
  - about.md
  - portfolio.md
  - intelligence.md
  - archive.md
  - contact.md


style: dark

google_analytics: G-F3VRC5GNYL

plugins:
  - jekyll-seo-tag